config/routes.rb
InventoryProject::Application.routes.draw do
  resources :reports

  resources :sales

  resources :shipments

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :shipments
  has_many :sales

  validates_presence_of :category, :price
  validates :price, numericality: {greater_than_or_equal_to: 0}

  validates_presence_of :category, :quantityInStock
  validates :quantityInStock, numericality: {greater_than_or_equal_to: 0}

  def total_count
    total_count = 0
    Shipment.all.each do |c|
      total_count += c.quantity
    end
    total_count
  end

  def total_sold
    total_sold = 0
    Sale.all.each do |c|
      total_sold += c.quantity
    end
    total_sold
  end

  def quantityInStock
  (stock_all - total_sold)
  end



  def stock_all
    stock_all = 0
    Shipment.all.each do |c|
      stock_all += c.quantity
    end
    stock_all
  end


  def low
    if quantityInStock < 5
      "Restock"
    else "Enough in stock"
    end
  end




  def sum_sold
    Shipment.sum( :quantity)
  end

  def sum_order
    Shipment.sum(:quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category, :price, :quantityInStock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Available Products</h1>

<table>
  <thead>
    <tr>

      <th>Category</th>
      <th>Price</th>
      <th>Status</th>

    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>

        <td><%= product.category %></td>
        <td><%= number_to_currency(product.price )%></td>


        <td><%= product.low %></td>


        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Category:</strong>
  <%= @product.category %>

</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
</center>
<p>
  <strong>Quantity InStock:</strong>
  <%= @product.quantityInStock  %>


</p>



<%@product.shipments.each do |shipment| %>

    <strong>Shipment Quantity:</strong>
    <p><%=shipment.quantity %></p>
    <p><%=number_to_currency(shipment.quantity * @product.price) %></p>
    <strong>Date of shipment:</strong>
    <p><%=shipment.DateIn %></p>

    <% end %>

<%@product.sales.each do |sale| %>

    <strong>Sales:</strong>
    <p><%=sale.quantity %></p>
    <p><%=number_to_currency(sale.quantity * @product.price) %></p>
    <strong>Date of sale:</strong>
    <p><%=sale.dateOut %></p>

<% end %>









<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>