config/routes.rb
InventoryProject::Application.routes.draw do
  resources :reports

  resources :sales

  resources :shipments

  resources :products

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base

  belongs_to :product

  validates_presence_of :product_id, :quantity
  validates :quantity, numericality: {greater_than_or_equal_to: 0}

end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.new(shipment_params)

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shipment }
      else
        format.html { render action: 'new' }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:product_id, :quantity, :DateIn)
    end
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/_form.html.erb
<%= form_for(@shipment) do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :category %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :DateIn %><br>
    <%= f.date_select :DateIn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editing shipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipment %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/index.html.erb
<h1>Listing shipments</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Date Received</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= shipment.product_id %></td>
        <td><%= shipment.quantity %></td>
        <td><%= shipment.DateIn %></td>
        <td><%= link_to 'Show', shipment %></td>
        <td><%= link_to 'Edit', edit_shipment_path(shipment) %></td>
        <td><%= link_to 'Destroy', shipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/new.html.erb
<h1>New shipment</h1>

<%= render 'form' %>

<%= link_to 'Back', shipments_path %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @shipment.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @shipment.quantity %>
</p>

<p>
  <strong>Datein:</strong>
  <%= @shipment.DateIn %>
</p>

<%= link_to 'Edit', edit_shipment_path(@shipment) %> |
<%= link_to 'Back', shipments_path %>