config/routes.rb
InventoryProject::Application.routes.draw do
  resources :reports

  resources :sales

  resources :shipments

  resources :products

end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :shipment
  belongs_to :sale
  belongs_to :product

  Report.delete_all

  def total_gross_revenue
    total_count = 0
    Sale.all.each do |r|
      total_count += r.saleRevenue
    end
    total_count
  end

  def week_avg_sold
    total_count = 0
    Sale.all.each do |s|
      total_count += s.quantity
    end
    total_count/52
end

  def total_sold
    total_count = 0
    Sale.all.each do |s|
      total_count += s.quantity
    end
    total_count
  end




  end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params[:report]
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Report</h1>

<table>
  <thead>
  <tr>
    <th>Total Gross Revenue</th>
    <th>Average Week Yearly</th>
    <th>Total Sales</th>

  </tr>
  </thead>

  <tbody>



  <% @reports.each do |report| %>
      <tr>
        <td><%= number_to_currency(report.total_gross_revenue) %></td>
        <td><%= report.week_avg_sold %></td>
        <td><%= report.total_sold %></td>



      </tr>


  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>